import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { FaReact } from 'react-icons/fa';
import { AiOutlineCopyrightCircle } from 'react-icons/ai';
import { DiJavascript } from 'react-icons/di';


export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Movie Hunting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em Destaque
        </h1>

        <Link href="busca">Ir para Busca</Link>

        <ul>
          {list.map(item => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width="150" /><br />
                {item.title}
              </a>
            </li>
          ))}
        </ul>
        
        <hr />
        <Link href="/sobre">Sobre</Link>
      </main>

       <footer>
         <div>
           <span><AiOutlineCopyrightCircle/>Developed by - Will Freittas with NextJs</span>
           <FaReact />
           <DiJavascript />
         </div>
       </footer>

    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/trending');
  const json = await res.json();

  return {
    props: {
      list: json.list
    }
  }
}
