import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css'

import { FaReact } from 'react-icons/fa';
import { AiOutlineCopyrightCircle } from 'react-icons/ai';
import { DiJavascript } from 'react-icons/di';

export default function Sobre({ author, role }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>The Movie Hunting</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Sobre
                </h1>

                Desenvolvido durante estudo sobre NextJs, para ser exibido em <a href="https://i-portifolio.vercel.app/" target="_blank" >Portfolio</a>
                Estamos em processo de construção, portanto, algumas atualizações ainda estão sendo implpementadas.
                <hr />
                Author: {author}<br />
                Skill: {role}

                <Link href="/">voltar para o início</Link>

            </main>

            <footer>
         <div>
           <span><AiOutlineCopyrightCircle/>Developed by - Will Freittas with NextJs</span>
           <FaReact />
           <DiJavascript />
         </div>
       </footer>
        </div>
    )
}

export async function getStaticProps() {
    return {
        props: {
            author: 'Will Freittas',
            role: 'Frontend Apprentice'
        }
    }
}
